apiVersion: apps/v1
kind: Deployment
metadata:
  name: vidly-db-deployment
  namespace: vidly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vidly
  template:
    metadata:
      labels:
        app: vidly
    spec:
      containers:
      - name: vidly-db
        image: docker.io/nickdraper/vidly-db:latest
        ports:
        - containerPort: 8000
